global.data = {
    islogin: false,
    userid: '',
    user: {
    },
    shujulist:'',
    token:'eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1NDU4ODgyMzUsInN1YiI6IjE4MjYyMjYwMjczIiwiYXVkaWVuY2UiOjEsImNyZWF0ZWQiOjE1NDMyOTYyMzUwODN9.OwlokXRfI2YjWCSw8bBdO9-K3smwaswCgyfnDxzY72UZX5_eLFX_4v9k_0uPYLS7Gd0rbMvGpirwsAiZusrfHQ',
    usershoplist: [

        {
            "sortBy": 41,
            "areaId": 1,
            "abbr": "配送中心（旺达）",
            "telephone": "1",
            "storeAttribute": "HEAD",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": true,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1527823157,
            "enable": true,
            "storeType": "SHOP",
            "name": "配送中心（旺达）",
            "id": 6
        },
        {
            "sortBy": 40,
            "areaId": 1,
            "abbr": "甪直四店",
            "telephone": "1",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1527214886,
            "enable": true,
            "storeType": "SHOP",
            "name": "甪直四店",
            "id": 17
        },
        {
            "sortBy": 39,
            "areaId": 1,
            "abbr": "甪直一店",
            "telephone": "1",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1496293883,
            "enable": true,
            "storeType": "SHOP",
            "name": "甪直一店",
            "id": 8
        },
        {
            "sortBy": 37,
            "areaId": 1,
            "abbr": "花桥店",
            "telephone": "1",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": true,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "printHeader": "",
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "花桥店",
            "id": 1
        },
        {
            "sortBy": 36,
            "areaId": 1,
            "abbr": "吴江柳胥店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江柳胥店",
            "id": 2
        },
        {
            "sortBy": 35,
            "areaId": 1,
            "abbr": "跨塘三",
            "telephone": "1",
            "storeAttribute": "PARTNER",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1493039108,
            "enable": true,
            "storeType": "SHOP",
            "name": "跨塘三",
            "id": 3
        },
        {
            "sortBy": 34,
            "areaId": 1,
            "abbr": "东张店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492061439,
            "enable": true,
            "storeType": "SHOP",
            "name": "东张店",
            "id": 4
        },
        {
            "sortBy": 33,
            "areaId": 1,
            "abbr": "马涧景山店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "马涧景山店",
            "id": 5
        },
        {
            "sortBy": 32,
            "areaId": 1,
            "abbr": "吴江芦墟店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江芦墟店",
            "id": 7
        },
        {
            "sortBy": 31,
            "areaId": 1,
            "abbr": "斜塘二店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "斜塘二店",
            "id": 9
        },
        {
            "sortBy": 30,
            "areaId": 1,
            "abbr": "马涧二店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "马涧二店",
            "id": 10
        },
        {
            "sortBy": 29,
            "areaId": 1,
            "abbr": "吴江七都店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江七都店",
            "id": 11
        },
        {
            "sortBy": 28,
            "areaId": 1,
            "abbr": "跨塘四店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "跨塘四店",
            "id": 12
        },
        {
            "sortBy": 27,
            "areaId": 1,
            "abbr": "马涧一店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "马涧一店",
            "id": 13
        },
        {
            "sortBy": 26,
            "areaId": 1,
            "abbr": "黄埭店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "黄埭店",
            "id": 14
        },
        {
            "sortBy": 25,
            "areaId": 1,
            "abbr": "斜塘旗舰店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "斜塘旗舰店",
            "id": 15
        },
        {
            "sortBy": 24,
            "areaId": 1,
            "abbr": "浒关店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "浒关店",
            "id": 16
        },
        {
            "sortBy": 23,
            "areaId": 1,
            "abbr": "万客隆店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "万客隆店",
            "id": 18
        },
        {
            "sortBy": 22,
            "areaId": 1,
            "abbr": "吴江市区店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江市区店",
            "id": 19
        },
        {
            "sortBy": 21,
            "areaId": 1,
            "abbr": "斜塘三店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "斜塘三店",
            "id": 20
        },
        {
            "sortBy": 20,
            "areaId": 1,
            "abbr": "唯亭店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": true,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492499877,
            "enable": true,
            "storeType": "SHOP",
            "name": "唯亭店",
            "id": 22
        },
        {
            "sortBy": 19,
            "areaId": 1,
            "abbr": "吴江黎里店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": true,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492074841,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江黎里店",
            "id": 23
        },
        {
            "sortBy": 18,
            "areaId": 1,
            "abbr": "跨塘五店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": true,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1493039383,
            "enable": true,
            "storeType": "SHOP",
            "name": "跨塘五店",
            "id": 24
        },
        {
            "sortBy": 17,
            "areaId": 1,
            "abbr": "吴江三里桥店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江三里桥店",
            "id": 25
        },
        {
            "sortBy": 16,
            "areaId": 1,
            "abbr": "天虹店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "天虹店",
            "id": 26
        },
        {
            "sortBy": 15,
            "areaId": 1,
            "abbr": "长江花园店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": true,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492075333,
            "enable": true,
            "storeType": "SHOP",
            "name": "长江花园店",
            "id": 27
        },
        {
            "sortBy": 14,
            "areaId": 1,
            "abbr": "总部库存仓",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "总部库存仓",
            "id": 28
        },
        {
            "sortBy": 13,
            "areaId": 1,
            "abbr": "国检店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "国检店",
            "id": 29
        },
        {
            "sortBy": 12,
            "areaId": 1,
            "abbr": "胥口店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "胥口店",
            "id": 30
        },
        {
            "sortBy": 11,
            "areaId": 1,
            "abbr": "望亭店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "望亭店",
            "id": 31
        },
        {
            "sortBy": 10,
            "areaId": 1,
            "abbr": "张浦店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "张浦店",
            "id": 32
        },
        {
            "sortBy": 9,
            "areaId": 1,
            "abbr": "吴市店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴市店",
            "id": 33
        },
        {
            "sortBy": 8,
            "areaId": 1,
            "abbr": "吴江花港店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "吴江花港店",
            "id": 34
        },
        {
            "sortBy": 6,
            "areaId": 1,
            "abbr": "翰林店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "SHOP",
            "name": "翰林店",
            "id": 36
        },
        {
            "sortBy": 5,
            "areaId": 1,
            "abbr": "郭巷店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": true,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492072021,
            "enable": true,
            "storeType": "SHOP",
            "name": "郭巷店",
            "id": 37
        },
        {
            "sortBy": 4,
            "areaId": 1,
            "abbr": "蠡口店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492072069,
            "enable": true,
            "storeType": "SHOP",
            "name": "蠡口店",
            "id": 38
        },
        {
            "sortBy": 3,
            "areaId": 1,
            "abbr": "样机、备用机仓",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1493038995,
            "enable": true,
            "storeType": "SHOP",
            "name": "样机、备用机仓",
            "id": 39
        },
        {
            "sortBy": 2,
            "areaId": 1,
            "abbr": "黄桥店",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1492500996,
            "enable": true,
            "storeType": "SHOP",
            "name": "黄桥店",
            "id": 40
        },
        {
            "sortBy": 1,
            "areaId": 1,
            "abbr": "售后新仓",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": true,
            "salesShiftFlag": false,
            "areaSortBy": 2,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 1512110732,
            "enable": true,
            "storeType": "SHOP",
            "name": "售后新仓",
            "id": 41
        },
        {
            "sortBy": 1,
            "areaId": 3,
            "abbr": "A",
            "telephone": "1",
            "storeAttribute": "DIRECT",
            "inventoryCheckingFlag": false,
            "salesShiftReturnMainFlag": false,
            "inventoryFlag": false,
            "salesShiftFlag": false,
            "areaSortBy": 1,
            "accountDiscount": {
                "sortBy": 0,
                "createDateline": 1543545848,
                "createDate": "2018-11-30 10:44:08",
                "displayInfo": "0-null-null-null",
                "enable": false,
                "id": 0
            },
            "initPayableFlag": false,
            "salecloseDateline": 0,
            "salecloserOperateDateline": 0,
            "lastInventoryCheckDateline": 0,
            "enable": true,
            "storeType": "DEPT",
            "name": "A",
            "id": 43
        }
    ],
    shoppinglist: [

    ],
    tcount: [],
    yCount:[

    ],
    yCountweek:[

    ],
    yCountmonth:[

    ],
    tip:'',
    dataList:'',
    allRootCategories:[]


}